In [148]:
import pandas as pd
from IPython.display import display, HTML

In [90]:
sd = 10000

In [94]:
def getfromuser():
    gi = 90000
    nd = 3
    ft = 'single'
    return gi,nd,ft

In [65]:
def tax_rate_single(inc):
    if (inc >= 0 and inc < 9700):
        return 10
    elif (inc >= 9701 and inc < 39475):
        return 12
    elif (inc >= 39476 and inc < 84200):
        return 22
    elif (inc >= 84201 and inc < 160725):
        return 24
    elif (inc >= 160726 and inc < 204100):
        return 32
    elif (inc >= 204101 and inc < 510300):
        return 35
    elif (inc >= 510301):
        return 37

In [66]:
def tax_rate_married(inc):
    if (inc >= 0 and inc < 19400):
        return 10
    elif (inc >= 19401 and inc < 78950):
        return 12
    elif (inc >= 78951 and inc < 168400):
        return 22
    elif (inc >= 168401 and inc < 321450):
        return 24
    elif (inc >= 321451 and inc < 408200):
        return 32
    elif (inc >= 408201 and inc < 612350):
        return 35
    elif (inc >= 612351):
        return 37

In [67]:
def tax_rate_headofhousehold(inc):
    if (inc >= 0 and inc < 13850):
        return 10
    elif (inc >= 13851 and inc < 52850):
        return 12
    elif (inc >= 52851 and inc < 84200):
        return 22
    elif (inc >= 84201 and inc < 160700):
        return 24
    elif (inc >= 160701 and inc < 204100):
        return 32
    elif (inc >= 204101 and inc < 510300):
        return 35
    elif (inc >= 510301):
        return 37

In [68]:
def calc_tax_rate(status, ti):
    if status == 'single':
        tr = tax_rate_single(ti)
        return tr
    elif status == 'married filing jointly':
        tr = tax_rate_married(ti)
        return tr
    elif status == 'head of household':
        tr = tax_rate_headofhousehold(ti)
        return tr

In [81]:
def calc_taxable_inc(gi, sd, dd):
    ti = gi - sd - dd
    if ti > 0:
        return ti
    else:
        return 0

In [82]:
def calc_inc_tax(ti, tr):
    inc_tax = ti * tr
    return inc_tax

In [83]:
def calc_dd(dependents):
    dd = dependents * 2000
    return dd

In [101]:
def get_tax_info():
    tax_info = [[10000, 0, 'single'],
                [10000, 1, 'married filing jointly'],
                [20000, 3, 'married filing jointly'],
                [20000, 1, 'head of household'],
                [40000, 2, 'single'],
                [90000, 3, 'single'],
                [60000, 2, 'head of household'],
                [90000, 3, 'head of household'],
                [170000, 4, 'head of household'],
                [80000, 0, 'married filing jointly'],
                [185000, 4, 'married filing jointly'],
                [170000, 1, 'single'],
                [25000, 2, 'single'],
                [400000, 1, 'married filing jointly']]
    return tax_info

In [126]:
def start_calc(gross_inc, dependents, filer_type):
#     gross_inc, dependents, filer_type = getfromuser()
#     print("gross_inc, dependents, filer_type : ", gross_inc, dependents, filer_type)
    dd = calc_dd(dependents)
#     print("Dependents deduction : ", dd)
    taxable_inc = calc_taxable_inc(gross_inc, sd, dd)
#     print("taxable Income : ", taxable_inc)
    tax_rate = calc_tax_rate(filer_type, taxable_inc)
#     print("Tax rate : ", tax_rate)
    inc_tax = calc_inc_tax(taxable_inc, tax_rate)
#     print("Income tax : ", inc_tax)
    return inc_tax

In [145]:
def create_df(lst):
    df = pd.DataFrame(lst, columns = ['Number of Dependents', 'Gross Income', 'Filer Type', 'Expected Income Tax'])
    return df

In [149]:
def main():
    tax_info = get_tax_info()
    lst =[]
    for entry in tax_info:
        gross_inc, dependents, filer_type = entry
#         print(gross_inc, dependents, filer_type)
        inc_tax = start_calc(gross_inc, dependents, filer_type)
        lst_val = [dependents, gross_inc, filer_type, inc_tax]
        lst.append(lst_val)
    tax_info_table = create_df(lst)
#     print(tax_info_table)
    display(tax_info_table)

In [150]:
if __name__ == "__main__":
    main()

,Number of Dependents,Gross Income,Filer Type,Expected Income Tax
0,0,10000,single,0
1,1,10000,married filing jointly,0
2,3,20000,married filing jointly,40000
3,1,20000,head of household,80000
4,2,40000,single,312000
5,3,90000,single,1628000
6,2,60000,head of household,552000
7,3,90000,head of household,1628000
8,4,170000,head of household,3648000
9,0,80000,married filing jointly,840000
10,4,185000,married filing jointly,3674000
11,1,170000,single,3792000
12,2,25000,single,132000
13,1,400000,married filing jointly,12416000